# Page settings

baseURL = "https://emil.tbjerglund.dk/"
languageCode = "en"
title = "Emil Tveden Bjerglund - Data Scientist"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "Emil T. Bjerglund"
    description = "Emil Tveden Bjerglund - Data Scientist - CV"


    primaryColor = "#3260a8"
    textPrimaryColor = "#202020"




    [params.profile]
        enable = true
        name = "Emil T. Bjerglund"
        tagline = "Data Scientist"
        avatar = "profile.png"







    [params.contact]
        enable = true
        location = "Silkeborg, Denmark"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+45 52 23 24 00"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "emil@tbjerglund.dk"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "emil.tbjerglund.dk"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Python - R - SAS"
        [[params.skills.list.items]]
        details = "SQL Server"
        [[params.skills.list.items]]
        details = "Advanced analytics"
        [[params.skills.list.items]]
        details = "ETL systems"
        [[params.skills.list.items]]
        details = "Design and implementation of analytical solutions"







    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Ph.d. in nanoscience"
        university = "Aarhus University"
        dates = "2013 - 2018"
        [[params.education.list]]
        degree = "M.Sc. in nanoscience"
        university = "Aarhus University"
        dates = "2013-2016"
        [[params.education.list]]
        degree = "B.Sc. in nanoscience"
        university = "Aarhus University"
        dates = "2010-2013"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Danish"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Scouting and outdoor life"
        [[params.interests.list]]
        name = "Kettlebell training"
        [[params.interests.list]]
        name = "Science"
        [[params.interests.list]]
        name = "Technology"








    [params.summary]
        enable = true
        text = "Data science is a passion to me and I continously seek to develop my skills and expand my knowledge, both at work and in my spare time. The starting for me is always to understand the stakeholders specific questions and the decisions they are facing, in order to devise the solution that contributes the most value to their business. I have collected and analysed high-dimensional data to help customers answer specific questions about their products, in order to guide new development efforts, predict sample behaviour and reliability at different conditions and solve specific production issues. I am a strong communicator, capable of breaking down technical topics to facilitate discussion with stakeholders. I have a multidisciplinary background within nanoscience, materials science, organic surface chemistry and surface physics. During my studies I developed a strong interest in hyperspectral analysis (Raman spectroscopy, Electron Energy Loss Spectroscopy etc.) and in particular the data science skills and tools that was necessary to draw sensible information from these large datasets."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Data Warehouse Developer"
        dates = "2021 - Present"
        company = "Jyske Bank"
        details = "Currently I work as Data Warehouse Developer in Jyske Bank, developing efficient ETL (extract, transform, load) data flows, consulting with model developers on best strategies for data preparation as well as monitoring and optimising daily data flows.This is the foundation of Jyske Banks credit modelling. My responsibilities include:"
        [[params.experience.list.items]]
        details = "Development of ETL processes for preparing model data."
        [[params.experience.list.items]]
        details = "Automation of data pipelines."
        [[params.experience.list.items]]
        details = "Refining and optimising the existing codebase."


        
        [[params.experience.list]]
        title = "Consultant"
        dates = "2018-2021"
        company = "Danish Technological Institute"
        details = "At DTI I worked as a consultant helping companies from many industries (automotive, wind energy, pharmaceuticals, food production etc.) with analysis of materials, product development and process optimisation. "
        [[params.experience.list.items]]
        details = "Materials characterisation and advanced data analytics"
        [[params.experience.list.items]]
        details = "Process optimisation"
        [[params.experience.list.items]]
        details = "Product development"

    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."










    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/emiltb"
        title = "emiltb"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/emiltb"
        title = "emiltb"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/emilbp"
        title = "@emilbp"





